name: weather
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.5 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  flutter_svg: ^1.1.6

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/logo/
    - assets/icon/
    - assets/image/
  fonts:
    - family: GoogleSans
      fonts:
        - asset: assets/font/ProductSans-Bold.ttf
          weight: 700
        - asset: assets/font/ProductSans-medium.ttf
          weight: 400
        - asset: assets/font/ProductSans-Regular.ttf
